name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the 'main' branch
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Ensure this matches the version you use locally

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the project
    - name: Build the project
      run: npm run build

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase
      run: firebase deploy
